### ISSUE TITLE
CSS color is not rendered

### ISSUE THREAD

**Issue by JunjieW** [nea/MarkdownViewerPlusPlus#32]
Hi,

I was trying to add some customized CSS, but it wasn't rendered well. I'm not sure if it's caused by the HTMLRenderer or in this plugin. The exported html can be rendered as expected in Chrome, IE, Firefox.

```css
body {
    font-family: "Source Sans Pro",sans-serif;
    font-size: 13px;
    color: #3f3f3f
}
h1 {    font-size: 25px; }
h2 {    font-size: 23px; }
h3 {    font-size: 21px; }
h4 {    font-size: 19px; }
h5 {    font-size: 16px; }
h1, h2, h3, h4, h5, h6 {
    font-family: inherit;
} 
blockquote {
  background: #f9f9f9;
  border-left: 10px solid #ccc;
  padding-top: 5px;
  padding-bottom: 5px;
  quotes: "\201C""\201D""\2018""\2019";
}

code {
    font-family: Monaco, Consolas, "Andale Mono", "DejaVu Sans Mono", monospace;
    font-size: 95%;
    white-space: pre;
    white-space: pre-wrap;
    white-space: -moz-pre-wrap;
    white-space: -o-pre-wrap;
    background: rgb(200,200,200);
    display: inline-block;
}
pre code {
    font-family: Monaco, Consolas, "Andale Mono", "DejaVu Sans Mono", monospace;
    font-size: 95%;
    line-height: 140%;
    white-space: pre;
    white-space: pre-wrap;
    white-space: -moz-pre-wrap;
    white-space: -o-pre-wrap;
    background: #faf8f0;
    display: block;
    padding: 0.5em 1em;
    border: 1px solid #bebab0;
}
```
