### ISSUE TITLE
Monospaced text is higher than regular text

### ISSUE THREAD

**Issue by oldmud0** [nea/MarkdownViewerPlusPlus#41]
Example:
![cswnsoo](https://cloud.githubusercontent.com/assets/5247009/26758280/66178216-489f-11e7-892b-1164590f38eb.png)
(that last letter is a 't' if it bothers you)

This might be MacType's doing again, but I have MacType off for Notepad++.

**Comment by stezmi** [comment]
This is just a style issue; you could adjust the appearance by adding some *Custom CSS*. This will be different based on the fonts available. Try, for example:

```css
body {
  font: 15px helvetica, arial, sans-serif;
}

pre, code {
  font: 14px consolas, monaco, monospace;
}
```

It might be nice for a more complete default stylesheet to be included, but meanwhile the custom CSS provides a nice way to apply your own. (Note that there are currently some issues with custom CSS that you might need to be aware of).
