### ISSUE TITLE
[Feature Request] Use NPP Style Configurator Colors

### ISSUE THREAD

**Issue by Matlock42** [nea/MarkdownViewerPlusPlus#90]
Would it be possible to have the rendered view use the theme colors as selected in the Style Configurator? I use a white text on black bg theme (Deep Black) and the contrast is quite shocking. I wouldn't think this to be too hard.

For now, I can set the Custom CSS to:
``` css
body {
    background-color: black;
    color: white;
}
```
Thanks and great work!!!
